package seed

import "github.com/prompt-masters/backend/internal/domain"

const criterionMaxScore = 10

// limits tightens the time and prompt budget as difficulty rises.
var limits = map[domain.Difficulty]struct {
	timeLimitSeconds int
	maxPromptChars   int
	passingScore     int
}{
	domain.DifficultyEasy:   {timeLimitSeconds: 300, maxPromptChars: 800, passingScore: 60},
	domain.DifficultyMedium: {timeLimitSeconds: 240, maxPromptChars: 500, passingScore: 70},
	domain.DifficultyHard:   {timeLimitSeconds: 180, maxPromptChars: 300, passingScore: 80},
}

type rules struct {
	forbidden []string
	required  []string
	format    string
}

func challenge(
	slug string,
	category domain.Category,
	difficulty domain.Difficulty,
	title, description string,
	r rules,
	criteria ...domain.JudgeCriterion,
) *domain.Challenge {
	l := limits[difficulty]
	forbidden, required := r.forbidden, r.required
	if forbidden == nil {
		forbidden = []string{}
	}
	if required == nil {
		required = []string{}
	}
	return &domain.Challenge{
		Slug:        slug,
		Title:       title,
		Description: description,
		Category:    category,
		Difficulty:  difficulty,
		Constraints: domain.ChallengeConstraints{
			TimeLimitSeconds: l.timeLimitSeconds,
			MaxPromptChars:   l.maxPromptChars,
			ForbiddenWords:   forbidden,
			RequiredElements: required,
			OutputFormat:     r.format,
		},
		JudgeCriteria: domain.JudgeCriteria{
			PassingScore: l.passingScore,
			Criteria:     criteria,
		},
	}
}

func criterion(name string, weight float64, description string) domain.JudgeCriterion {
	return domain.JudgeCriterion{Name: name, Description: description, Weight: weight, MaxScore: criterionMaxScore}
}

// Challenges returns the development challenge set: three challenges for
// every category and difficulty pair.
func Challenges() []*domain.Challenge {
	const (
		creative   = domain.CategoryCreativeWriting
		coding     = domain.CategoryCoding
		extraction = domain.CategoryDataExtraction
		summary    = domain.CategorySummarization
		reasoning  = domain.CategoryReasoning

		easy   = domain.DifficultyEasy
		medium = domain.DifficultyMedium
		hard   = domain.DifficultyHard
	)

	return []*domain.Challenge{
		// Creative writing
		challenge("creative-easy-haiku-seasons", creative, easy,
			"Seasonal Haiku",
			"Write a prompt that makes the model produce a haiku about the first day of autumn.",
			rules{required: []string{"three lines", "5-7-5 syllable pattern"}, format: "plain_text"},
			criterion("form", 0.4, "The output has exactly three lines following a 5-7-5 syllable pattern."),
			criterion("theme", 0.3, "The haiku clearly evokes the first day of autumn."),
			criterion("imagery", 0.3, "Uses concrete sensory imagery rather than abstract statements."),
		),
		challenge("creative-easy-product-slogan", creative, easy,
			"Coffee Shop Slogan",
			"Write a prompt that makes the model create five catchy slogans for a neighbourhood coffee shop called Bean There.",
			rules{required: []string{"five slogans", "the shop name"}, format: "numbered_list"},
			criterion("count_and_format", 0.3, "Exactly five slogans, presented as a numbered list."),
			criterion("brand_fit", 0.3, "Every slogan mentions or plays on the name Bean There."),
			criterion("catchiness", 0.4, "Slogans are short, memorable and varied in style."),
		),
		challenge("creative-easy-bedtime-story", creative, easy,
			"Bedtime Story Opening",
			"Write a prompt that makes the model write the first paragraph of a bedtime story about a shy dragon, suitable for a five-year-old.",
			rules{required: []string{"a shy dragon", "age-appropriate language"}, format: "plain_text"},
			criterion("audience_fit", 0.4, "Vocabulary and tone suit a five-year-old; nothing frightening."),
			criterion("character", 0.3, "The dragon's shyness is shown through actions or dialogue."),
			criterion("hook", 0.3, "The paragraph makes a child want to hear what happens next."),
		),
		challenge("creative-medium-six-word-stories", creative, medium,
			"Six-Word Stories",
			"Write a prompt that makes the model produce three six-word stories, each in a different genre: horror, romance and science fiction.",
			rules{forbidden: []string{"six", "story"}, required: []string{"exactly six words each", "genre label"}, format: "numbered_list"},
			criterion("word_count", 0.35, "Each story contains exactly six words."),
			criterion("genre_accuracy", 0.35, "Each story unmistakably belongs to its labelled genre."),
			criterion("narrative_impact", 0.3, "Each story implies a complete arc or twist despite its length."),
		),
		challenge("creative-medium-villain-monologue", creative, medium,
			"Sympathetic Villain",
			"Write a prompt that makes the model write a 150-word monologue in which a villain justifies flooding a city, so that the reader partly sympathises.",
			rules{forbidden: []string{"sympathetic", "villain"}, required: []string{"first-person voice", "a clear motive"}, format: "plain_text"},
			criterion("voice", 0.3, "Consistent first-person voice with a distinct personality."),
			criterion("motive", 0.4, "The motive is coherent and makes the villain partly sympathetic."),
			criterion("length", 0.3, "Between 130 and 170 words."),
		),
		challenge("creative-medium-limerick-cat", creative, medium,
			"Limerick for a Cat Café",
			"Write a prompt that makes the model write a limerick advertising a cat café's new weekend brunch menu.",
			rules{forbidden: []string{"limerick"}, required: []string{"AABBA rhyme scheme", "the brunch menu"}, format: "plain_text"},
			criterion("form", 0.4, "Five lines with an AABBA rhyme scheme and limerick rhythm."),
			criterion("message", 0.3, "Clearly advertises the weekend brunch menu."),
			criterion("humour", 0.3, "The limerick is playful and genuinely funny."),
		),
		challenge("creative-hard-reverse-chronology", creative, hard,
			"Backwards Breakup",
			"Write a prompt that makes the model tell the story of a breakup in five short scenes presented in reverse chronological order, ending with the couple's first meeting.",
			rules{forbidden: []string{"reverse", "backwards", "breakup"}, required: []string{"five scenes", "ends with first meeting"}, format: "markdown"},
			criterion("structure", 0.35, "Exactly five scenes in strict reverse chronological order."),
			criterion("emotional_arc", 0.35, "Emotion shifts believably from bitterness to hope across scenes."),
			criterion("craft", 0.3, "Scenes are vivid and economical, with no filler."),
		),
		challenge("creative-hard-lipogram", creative, hard,
			"The Missing Letter",
			"Write a prompt that makes the model write an 80-word description of a beach at sunset without using the letter 'e' anywhere.",
			rules{forbidden: []string{"lipogram", "letter e"}, required: []string{"no letter e", "about 80 words"}, format: "plain_text"},
			criterion("constraint", 0.5, "The output contains no letter 'e' in any word."),
			criterion("coherence", 0.3, "The text reads naturally and clearly describes a beach at sunset."),
			criterion("length", 0.2, "Between 70 and 90 words."),
		),
		challenge("creative-hard-unreliable-narrator", creative, hard,
			"Unreliable Narrator",
			"Write a prompt that makes the model write a 200-word diary entry whose narrator claims to be the victim, while clues reveal they caused the incident.",
			rules{forbidden: []string{"unreliable", "twist", "clue"}, required: []string{"diary format", "at least two hidden clues"}, format: "plain_text"},
			criterion("subtlety", 0.4, "Clues are discoverable on a careful reading but not stated outright."),
			criterion("consistency", 0.3, "The narrator's self-serving voice stays consistent throughout."),
			criterion("format_and_length", 0.3, "Reads as a dated diary entry of 180 to 220 words."),
		),

		// Coding
		challenge("coding-easy-fizzbuzz-variant", coding, easy,
			"FizzBuzz with a Twist",
			"Write a prompt that makes the model write a Python function that prints numbers 1 to 50, printing 'Fizz' for multiples of 4, 'Buzz' for multiples of 6 and 'FizzBuzz' for multiples of both.",
			rules{required: []string{"a Python function", "multiples of 4 and 6"}, format: "python"},
			criterion("correctness", 0.5, "The code produces the correct output for every number from 1 to 50."),
			criterion("readability", 0.25, "Clear names and a simple control flow."),
			criterion("spec_adherence", 0.25, "Uses 4 and 6, not the classic 3 and 5, and wraps the logic in a function."),
		),
		challenge("coding-easy-palindrome-check", coding, easy,
			"Palindrome Checker",
			"Write a prompt that makes the model write a JavaScript function isPalindrome(str) that ignores case, spaces and punctuation.",
			rules{required: []string{"function named isPalindrome", "ignores case and punctuation"}, format: "javascript"},
			criterion("correctness", 0.5, "Returns correct results, including for 'A man, a plan, a canal: Panama'."),
			criterion("edge_cases", 0.25, "Handles empty strings and single characters."),
			criterion("readability", 0.25, "Concise, idiomatic JavaScript."),
		),
		challenge("coding-easy-sql-top-customers", coding, easy,
			"Top Customers Query",
			"Write a prompt that makes the model write a SQL query returning the five customers with the highest total order value from tables customers(id, name) and orders(id, customer_id, amount).",
			rules{required: []string{"a single SQL query", "top five by total"}, format: "sql"},
			criterion("correctness", 0.5, "Joins, groups and orders correctly, limiting to five rows."),
			criterion("schema_use", 0.25, "Uses only the given tables and columns."),
			criterion("clarity", 0.25, "Readable formatting and meaningful aliases."),
		),
		challenge("coding-medium-rate-limiter", coding, medium,
			"Token Bucket Rate Limiter",
			"Write a prompt that makes the model implement a thread-safe token bucket rate limiter in Go with an Allow() bool method.",
			rules{forbidden: []string{"token bucket", "mutex"}, required: []string{"Allow() bool method", "thread safety"}, format: "go"},
			criterion("correctness", 0.4, "Tokens refill at the configured rate and never exceed capacity."),
			criterion("concurrency", 0.35, "Safe under concurrent calls with no data races."),
			criterion("api_design", 0.25, "A clean constructor and an idiomatic Go API."),
		),
		challenge("coding-medium-debounce-hook", coding, medium,
			"React Debounce Hook",
			"Write a prompt that makes the model write a TypeScript React hook useDebouncedValue(value, delay) with correct cleanup.",
			rules{forbidden: []string{"setTimeout", "useEffect"}, required: []string{"TypeScript generics", "timer cleanup"}, format: "typescript"},
			criterion("correctness", 0.4, "Returns the value only after it has been stable for the delay."),
			criterion("cleanup", 0.3, "Clears pending timers on change and unmount."),
			criterion("typing", 0.3, "Generic typing preserves the input value's type."),
		),
		challenge("coding-medium-regex-validator", coding, medium,
			"Postcode Validator",
			"Write a prompt that makes the model write a Python function with a regular expression that validates UK postcodes, plus five test cases.",
			rules{forbidden: []string{"regex", "UK postcode"}, required: []string{"a validation function", "five test cases"}, format: "python"},
			criterion("correctness", 0.45, "The pattern accepts valid formats such as 'SW1A 1AA' and rejects invalid ones."),
			criterion("tests", 0.3, "Five meaningful tests that cover both valid and invalid input."),
			criterion("explanation", 0.25, "The pattern is explained or commented so it can be maintained."),
		),
		challenge("coding-hard-lru-cache", coding, hard,
			"O(1) LRU Cache",
			"Write a prompt that makes the model implement an LRU cache in Python with O(1) get and put, without using OrderedDict or functools.",
			rules{forbidden: []string{"LRU", "OrderedDict", "linked list"}, required: []string{"O(1) get and put", "no OrderedDict"}, format: "python"},
			criterion("correctness", 0.4, "Evicts the least recently used item and updates recency on get."),
			criterion("complexity", 0.35, "Both operations are O(1), using a hash map plus a doubly linked list."),
			criterion("constraint_adherence", 0.25, "Avoids OrderedDict, functools and other shortcuts."),
		),
		challenge("coding-hard-sql-gaps-islands", coding, hard,
			"Login Streaks",
			"Write a prompt that makes the model write a PostgreSQL query that finds each user's longest streak of consecutive login days from logins(user_id, login_date).",
			rules{forbidden: []string{"gaps and islands", "window function", "streak"}, required: []string{"longest streak per user", "PostgreSQL"}, format: "sql"},
			criterion("correctness", 0.5, "Handles duplicate logins on the same day and single-day streaks."),
			criterion("technique", 0.25, "Uses a sound grouping technique rather than a brute-force self-join."),
			criterion("clarity", 0.25, "CTEs or comments make the logic easy to follow."),
		),
		challenge("coding-hard-refactor-legacy", coding, hard,
			"Refactor Without Breaking",
			"Write a prompt that makes the model refactor a provided 60-line nested-if JavaScript pricing function into testable pure functions while preserving behaviour.",
			rules{forbidden: []string{"refactor", "clean code"}, required: []string{"behaviour preserved", "pure functions", "tests"}, format: "javascript"},
			criterion("behaviour_preservation", 0.4, "The output is identical to the original for every pricing branch."),
			criterion("structure", 0.35, "Logic is decomposed into small, named pure functions."),
			criterion("tests", 0.25, "Includes tests that pin down the original behaviour."),
		),

		// Data extraction
		challenge("extraction-easy-contact-card", extraction, easy,
			"Business Card to JSON",
			"Write a prompt that makes the model extract name, job title, email and phone number from a pasted business card into a JSON object.",
			rules{required: []string{"name", "title", "email", "phone"}, format: "json"},
			criterion("accuracy", 0.5, "Every field matches the source text exactly."),
			criterion("valid_json", 0.3, "The output is valid JSON with the requested keys."),
			criterion("no_hallucination", 0.2, "Fields missing from the card are null rather than invented."),
		),
		challenge("extraction-easy-recipe-ingredients", extraction, easy,
			"Recipe Ingredients",
			"Write a prompt that makes the model list every ingredient with its quantity and unit from a recipe written as prose.",
			rules{required: []string{"quantity", "unit", "ingredient"}, format: "json"},
			criterion("completeness", 0.4, "Every ingredient mentioned in the prose is captured."),
			criterion("accuracy", 0.4, "Quantities and units are parsed correctly, e.g. 'a pinch' has no numeric quantity."),
			criterion("structure", 0.2, "A consistent array of objects with the same keys."),
		),
		challenge("extraction-easy-meeting-date", extraction, easy,
			"Meeting Details from Email",
			"Write a prompt that makes the model pull the meeting date, time, location and attendees out of a casual scheduling email.",
			rules{required: []string{"date", "time", "location", "attendees"}, format: "json"},
			criterion("accuracy", 0.5, "Date, time, location and attendees are extracted correctly."),
			criterion("normalisation", 0.3, "Date in ISO 8601 and time in 24-hour format."),
			criterion("valid_json", 0.2, "The output is valid JSON."),
		),
		challenge("extraction-medium-invoice-lines", extraction, medium,
			"Invoice Line Items",
			"Write a prompt that makes the model convert OCR text of a messy invoice into line items with description, quantity, unit price and line total, and verify that the totals add up.",
			rules{forbidden: []string{"OCR", "invoice"}, required: []string{"line items", "totals check"}, format: "json"},
			criterion("accuracy", 0.4, "Line items and amounts match the source despite OCR noise."),
			criterion("validation", 0.35, "Flags any mismatch between line totals and the invoice total."),
			criterion("schema", 0.25, "Numbers are numeric types, not strings, in valid JSON."),
		),
		challenge("extraction-medium-review-sentiment", extraction, medium,
			"Aspect-Based Review Analysis",
			"Write a prompt that makes the model extract each product aspect mentioned in a set of ten reviews along with its sentiment and a supporting quote.",
			rules{forbidden: []string{"sentiment analysis", "aspect"}, required: []string{"aspect", "sentiment", "supporting quote"}, format: "json"},
			criterion("coverage", 0.35, "Captures every distinct aspect mentioned across the reviews."),
			criterion("sentiment_accuracy", 0.35, "Sentiment labels are correct, including mixed or sarcastic cases."),
			criterion("grounding", 0.3, "Each quote appears verbatim in the reviews."),
		),
		challenge("extraction-medium-resume-parse", extraction, medium,
			"Resume to Structured Profile",
			"Write a prompt that makes the model convert a free-form resume into a structured profile with skills, work history (company, role, start, end) and education.",
			rules{forbidden: []string{"resume", "CV"}, required: []string{"skills", "work history", "education"}, format: "json"},
			criterion("accuracy", 0.4, "Companies, roles and dates are correct."),
			criterion("date_handling", 0.3, "'Present' and partial dates are handled consistently."),
			criterion("schema", 0.3, "Output follows the requested nested structure exactly."),
		),
		challenge("extraction-hard-contract-clauses", extraction, hard,
			"Contract Risk Clauses",
			"Write a prompt that makes the model find every termination, liability-cap and auto-renewal clause in a 3-page contract, citing section numbers.",
			rules{forbidden: []string{"clause", "contract", "legal"}, required: []string{"section numbers", "clause type", "verbatim excerpt"}, format: "json"},
			criterion("recall", 0.4, "Finds every relevant clause, including ones not in obviously named sections."),
			criterion("precision", 0.3, "Does not mislabel unrelated clauses."),
			criterion("citation", 0.3, "Section numbers and excerpts match the document exactly."),
		),
		challenge("extraction-hard-table-from-prose", extraction, hard,
			"Earnings Call Metrics",
			"Write a prompt that makes the model build a quarter-by-quarter table of revenue, margin and guidance from an earnings call transcript where figures are spoken informally.",
			rules{forbidden: []string{"table", "extract", "metrics"}, required: []string{"per-quarter rows", "units normalised"}, format: "markdown_table"},
			criterion("accuracy", 0.45, "Figures such as 'a touch over two point one billion' are converted correctly."),
			criterion("attribution", 0.3, "Each figure is assigned to the correct quarter and metric."),
			criterion("uncertainty", 0.25, "Ambiguous figures are flagged rather than guessed."),
		),
		challenge("extraction-hard-entity-linking", extraction, hard,
			"Who Is Who",
			"Write a prompt that makes the model extract every person in a news article and resolve pronouns and nicknames to the same entity, listing each mention.",
			rules{forbidden: []string{"coreference", "entity", "NER"}, required: []string{"canonical name", "all mentions"}, format: "json"},
			criterion("resolution", 0.45, "Pronouns, titles and nicknames are merged into the correct person."),
			criterion("completeness", 0.3, "No person or mention is missed."),
			criterion("precision", 0.25, "Distinct people with similar names are not merged."),
		),

		// Summarization
		challenge("summary-easy-news-tldr", summary, easy,
			"News in Three Bullets",
			"Write a prompt that makes the model summarize a 600-word news article in exactly three bullet points.",
			rules{required: []string{"three bullet points"}, format: "bullet_list"},
			criterion("coverage", 0.4, "The bullets capture the article's most important facts."),
			criterion("faithfulness", 0.4, "No facts are invented or distorted."),
			criterion("format", 0.2, "Exactly three concise bullets."),
		),
		challenge("summary-easy-email-thread", summary, easy,
			"Email Thread Catch-Up",
			"Write a prompt that makes the model summarize a 12-message email thread into the decision reached and the open questions.",
			rules{required: []string{"decision", "open questions"}, format: "markdown"},
			criterion("decision_accuracy", 0.4, "States the final decision correctly, not an earlier proposal."),
			criterion("open_questions", 0.3, "Lists the unresolved questions."),
			criterion("brevity", 0.3, "Readable in under 30 seconds."),
		),
		challenge("summary-easy-product-description", summary, easy,
			"Product Page in One Sentence",
			"Write a prompt that makes the model condense a long product page for a standing desk into a single sentence under 25 words.",
			rules{required: []string{"one sentence", "under 25 words"}, format: "plain_text"},
			criterion("key_benefit", 0.4, "Conveys the product's main selling point."),
			criterion("length", 0.3, "A single sentence under 25 words."),
			criterion("faithfulness", 0.3, "Makes no claims that are not on the product page."),
		),
		challenge("summary-medium-meeting-actions", summary, medium,
			"Meeting Transcript to Action Items",
			"Write a prompt that makes the model turn a rambling 45-minute meeting transcript into action items with an owner and due date for each.",
			rules{forbidden: []string{"action items", "summarize"}, required: []string{"owner", "due date"}, format: "markdown_table"},
			criterion("completeness", 0.35, "Every commitment made in the meeting is captured."),
			criterion("attribution", 0.35, "Owners and dates match what was said; unknowns are marked TBD."),
			criterion("signal_to_noise", 0.3, "Excludes small talk and discarded ideas."),
		),
		challenge("summary-medium-research-abstract", summary, medium,
			"Paper for a Non-Expert",
			"Write a prompt that makes the model explain a machine learning paper's abstract to a high-school student in 100 words.",
			rules{forbidden: []string{"simple", "explain like"}, required: []string{"100 words", "no unexplained jargon"}, format: "plain_text"},
			criterion("accessibility", 0.35, "Any technical terms used are explained."),
			criterion("accuracy", 0.4, "The main contribution and result are represented correctly."),
			criterion("length", 0.25, "Between 90 and 110 words."),
		),
		challenge("summary-medium-changelog", summary, medium,
			"Release Notes from Commits",
			"Write a prompt that makes the model turn 40 raw git commit messages into user-facing release notes grouped into Features, Fixes and Breaking Changes.",
			rules{forbidden: []string{"changelog", "release notes"}, required: []string{"Features", "Fixes", "Breaking Changes"}, format: "markdown"},
			criterion("grouping", 0.35, "Each change is placed in the correct group."),
			criterion("audience", 0.35, "Rewritten for users; internal chores and refactors are omitted."),
			criterion("breaking_changes", 0.3, "Breaking changes are complete and clearly highlighted."),
		),
		challenge("summary-hard-multi-source", summary, hard,
			"Conflicting Sources",
			"Write a prompt that makes the model summarize three articles about the same event that disagree, clearly separating points of consensus from points of dispute.",
			rules{forbidden: []string{"summarize", "compare", "sources"}, required: []string{"consensus", "disputed points", "attribution"}, format: "markdown"},
			criterion("separation", 0.35, "Cleanly distinguishes agreed facts from contested claims."),
			criterion("attribution", 0.35, "Each disputed claim is attributed to the article that makes it."),
			criterion("neutrality", 0.3, "Does not take a side or editorialise."),
		),
		challenge("summary-hard-legal-plain-language", summary, hard,
			"Terms of Service, Decoded",
			"Write a prompt that makes the model rewrite a 2,000-word terms of service as the five things a user must know, each under 20 words, without losing legal meaning.",
			rules{forbidden: []string{"summarize", "plain English", "TL;DR"}, required: []string{"five points", "under 20 words each"}, format: "numbered_list"},
			criterion("prioritisation", 0.35, "Picks the terms most consequential to users, such as data use and arbitration."),
			criterion("fidelity", 0.4, "The simplifications do not change the legal meaning."),
			criterion("constraints", 0.25, "Exactly five points, each under 20 words."),
		),
		challenge("summary-hard-progressive", summary, hard,
			"Three Zoom Levels",
			"Write a prompt that makes the model summarize a long book chapter at three levels of detail: one sentence, one paragraph and one page, each consistent with the others.",
			rules{forbidden: []string{"summary", "levels", "detail"}, required: []string{"one sentence", "one paragraph", "one page"}, format: "markdown"},
			criterion("consistency", 0.35, "The three levels never contradict each other."),
			criterion("scaling", 0.35, "Each level adds detail rather than rephrasing the previous one."),
			criterion("faithfulness", 0.3, "Every level stays true to the chapter."),
		),

		// Reasoning
		challenge("reasoning-easy-word-problem", reasoning, easy,
			"Train Word Problem",
			"Write a prompt that makes the model solve a two-train meeting-time word problem and show each step of its working.",
			rules{required: []string{"step-by-step working", "final answer"}, format: "markdown"},
			criterion("correctness", 0.5, "The final answer is correct."),
			criterion("steps", 0.3, "Each step is shown and follows from the previous one."),
			criterion("clarity", 0.2, "The final answer is clearly stated with units."),
		),
		challenge("reasoning-easy-odd-one-out", reasoning, easy,
			"Odd One Out",
			"Write a prompt that makes the model pick the odd one out from 'whale, shark, dolphin, seal' and justify the choice.",
			rules{required: []string{"a single choice", "justification"}, format: "plain_text"},
			criterion("defensible_answer", 0.4, "The choice is defensible; shark as the only non-mammal is the strongest."),
			criterion("justification", 0.4, "The reasoning names the distinguishing property explicitly."),
			criterion("concision", 0.2, "The answer is brief and direct."),
		),
		challenge("reasoning-easy-schedule", reasoning, easy,
			"Meeting Slot Finder",
			"Write a prompt that makes the model find a 1-hour slot that works for three people given their busy calendars as text.",
			rules{required: []string{"a valid 1-hour slot", "explanation"}, format: "plain_text"},
			criterion("correctness", 0.5, "The proposed slot is free for all three people."),
			criterion("reasoning", 0.3, "Explains how the conflicts were ruled out."),
			criterion("completeness", 0.2, "Mentions alternatives when several slots exist."),
		),
		challenge("reasoning-medium-logic-grid", reasoning, medium,
			"Four Houses Puzzle",
			"Write a prompt that makes the model solve a four-house logic grid puzzle (owner, pet, drink) and prove that the solution is unique.",
			rules{forbidden: []string{"Einstein", "zebra puzzle"}, required: []string{"full assignment", "uniqueness argument"}, format: "markdown_table"},
			criterion("correctness", 0.45, "Every house's attributes are assigned correctly."),
			criterion("deduction", 0.35, "Each deduction cites the clue it relies on."),
			criterion("uniqueness", 0.2, "Argues that no other assignment satisfies the clues."),
		),
		challenge("reasoning-medium-fermi-estimate", reasoning, medium,
			"Piano Tuners in Hanoi",
			"Write a prompt that makes the model estimate the number of piano tuners in Hanoi, stating every assumption and giving a range.",
			rules{forbidden: []string{"Fermi", "estimate"}, required: []string{"explicit assumptions", "numeric range"}, format: "markdown"},
			criterion("assumptions", 0.35, "Assumptions are explicit and plausible for the local context."),
			criterion("arithmetic", 0.35, "The calculations follow correctly from the assumptions."),
			criterion("calibration", 0.3, "The range reflects the uncertainty honestly."),
		),
		challenge("reasoning-medium-bug-hypotheses", reasoning, medium,
			"Intermittent Checkout Failure",
			"Write a prompt that makes the model rank three hypotheses for why 2% of checkouts fail only on Mondays, and propose one test to distinguish each.",
			rules{forbidden: []string{"hypothesis", "debug", "root cause"}, required: []string{"three ranked hypotheses", "a test per hypothesis"}, format: "numbered_list"},
			criterion("plausibility", 0.35, "The hypotheses fit the Monday-only, 2% pattern, e.g. batch jobs or cache expiry."),
			criterion("discriminating_tests", 0.4, "Each test would confirm or rule out its hypothesis."),
			criterion("ranking", 0.25, "The ranking is justified by likelihood and evidence."),
		),
		challenge("reasoning-hard-knights-knaves", reasoning, hard,
			"Knights, Knaves and Spies",
			"Write a prompt that makes the model solve a five-person knights, knaves and spies puzzle and verify its answer against every statement.",
			rules{forbidden: []string{"knight", "knave", "liar"}, required: []string{"role for each person", "verification of every statement"}, format: "markdown"},
			criterion("correctness", 0.5, "Every person's role is identified correctly."),
			criterion("verification", 0.3, "Each statement is checked against the final assignment."),
			criterion("rigor", 0.2, "Does not guess; each branch of case analysis is closed."),
		),
		challenge("reasoning-hard-probability-trap", reasoning, hard,
			"The Two-Child Problem",
			"Write a prompt that makes the model correctly answer 'A family has two children, one is a boy born on a Tuesday; what is the probability both are boys?' and explain why the intuitive answer is wrong.",
			rules{forbidden: []string{"13/27", "Bayes", "conditional probability"}, required: []string{"exact fraction", "explanation of the intuitive error"}, format: "markdown"},
			criterion("correctness", 0.5, "Arrives at 13/27 with valid reasoning."),
			criterion("explanation", 0.3, "Explains why the Tuesday detail changes the answer from 1/3."),
			criterion("rigor", 0.2, "Enumerates or counts the sample space correctly."),
		),
		challenge("reasoning-hard-tradeoff-decision", reasoning, hard,
			"Build vs Buy",
			"Write a prompt that makes the model recommend whether a 12-person startup should build or buy an authentication system, using a weighted decision matrix and stating what would flip the decision.",
			rules{forbidden: []string{"pros and cons", "decision matrix", "build vs buy"}, required: []string{"weighted criteria", "recommendation", "flip conditions"}, format: "markdown_table"},
			criterion("criteria_quality", 0.3, "Criteria are relevant, e.g. security risk, time to market and cost, and the weights are justified."),
			criterion("consistency", 0.35, "The recommendation follows from the matrix scores."),
			criterion("sensitivity", 0.35, "Names concrete conditions that would change the recommendation."),
		),
	}
}
