// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetChallengeByID = `-- name: GetChallengeByID :one
SELECT id, slug, title, description, category, difficulty, constraints, judge_criteria, created_at, updated_at FROM challenges WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id pgtype.UUID) (*Challenge, error) {
	row := q.db.QueryRow(ctx, GetChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Constraints,
		&i.JudgeCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListChallenges = `-- name: ListChallenges :many
SELECT id, slug, title, description, category, difficulty, constraints, judge_criteria, created_at, updated_at FROM challenges
WHERE ($1::text IS NULL OR category = $1::text)
  AND ($2::text IS NULL OR difficulty = $2::text)
ORDER BY slug
`

type ListChallengesParams struct {
	Category   pgtype.Text
	Difficulty pgtype.Text
}

func (q *Queries) ListChallenges(ctx context.Context, arg ListChallengesParams) ([]*Challenge, error) {
	rows, err := q.db.Query(ctx, ListChallenges, arg.Category, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Challenge{}
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Difficulty,
			&i.Constraints,
			&i.JudgeCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertChallenge = `-- name: UpsertChallenge :one
INSERT INTO challenges (slug, title, description, category, difficulty, constraints, judge_criteria)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO UPDATE SET
    title          = EXCLUDED.title,
    description    = EXCLUDED.description,
    category       = EXCLUDED.category,
    difficulty     = EXCLUDED.difficulty,
    constraints    = EXCLUDED.constraints,
    judge_criteria = EXCLUDED.judge_criteria,
    updated_at     = NOW()
RETURNING id, slug, title, description, category, difficulty, constraints, judge_criteria, created_at, updated_at
`

type UpsertChallengeParams struct {
	Slug          string
	Title         string
	Description   string
	Category      string
	Difficulty    string
	Constraints   []byte
	JudgeCriteria []byte
}

func (q *Queries) UpsertChallenge(ctx context.Context, arg UpsertChallengeParams) (*Challenge, error) {
	row := q.db.QueryRow(ctx, UpsertChallenge,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Difficulty,
		arg.Constraints,
		arg.JudgeCriteria,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Difficulty,
		&i.Constraints,
		&i.JudgeCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
