// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddGamePlayer = `-- name: AddGamePlayer :exec
INSERT INTO game_players (game_id, user_id) VALUES ($1, $2)
`

type AddGamePlayerParams struct {
	GameID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) AddGamePlayer(ctx context.Context, arg AddGamePlayerParams) error {
	_, err := q.db.Exec(ctx, AddGamePlayer, arg.GameID, arg.UserID)
	return err
}

const CreateGame = `-- name: CreateGame :one
INSERT INTO games (room_code, host_id)
VALUES ($1, $2)
ON CONFLICT (room_code) WHERE status IN ('waiting', 'in_progress') DO NOTHING
RETURNING id, room_code, host_id, status, created_at, updated_at, started_at
`

type CreateGameParams struct {
	RoomCode string
	HostID   pgtype.UUID
}

// Returns no row when the room code is held by another active game.
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (*Game, error) {
	row := q.db.QueryRow(ctx, CreateGame, arg.RoomCode, arg.HostID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.HostID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
	)
	return &i, err
}

const CreateGameSettings = `-- name: CreateGameSettings :exec
INSERT INTO game_settings (game_id, rounds, time_per_round, difficulty, category, ai_model, max_players)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateGameSettingsParams struct {
	GameID       pgtype.UUID
	Rounds       int16
	TimePerRound int16
	Difficulty   string
	Category     string
	AiModel      string
	MaxPlayers   int16
}

func (q *Queries) CreateGameSettings(ctx context.Context, arg CreateGameSettingsParams) error {
	_, err := q.db.Exec(ctx, CreateGameSettings,
		arg.GameID,
		arg.Rounds,
		arg.TimePerRound,
		arg.Difficulty,
		arg.Category,
		arg.AiModel,
		arg.MaxPlayers,
	)
	return err
}

const GetActiveGameIDByRoomCode = `-- name: GetActiveGameIDByRoomCode :one
SELECT id FROM games
WHERE room_code = $1 AND status IN ('waiting', 'in_progress')
`

func (q *Queries) GetActiveGameIDByRoomCode(ctx context.Context, roomCode string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, GetActiveGameIDByRoomCode, roomCode)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const GetGameByID = `-- name: GetGameByID :one
SELECT g.id, g.room_code, g.host_id, g.status, g.created_at, g.updated_at, g.started_at, s.game_id, s.rounds, s.time_per_round, s.difficulty, s.category, s.ai_model, s.max_players, s.updated_at,
       (SELECT COUNT(*) FROM game_players p WHERE p.game_id = g.id)::int AS player_count
FROM games g
JOIN game_settings s ON s.game_id = g.id
WHERE g.id = $1
`

type GetGameByIDRow struct {
	Game        Game
	GameSetting GameSetting
	PlayerCount int32
}

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (*GetGameByIDRow, error) {
	row := q.db.QueryRow(ctx, GetGameByID, id)
	var i GetGameByIDRow
	err := row.Scan(
		&i.Game.ID,
		&i.Game.RoomCode,
		&i.Game.HostID,
		&i.Game.Status,
		&i.Game.CreatedAt,
		&i.Game.UpdatedAt,
		&i.Game.StartedAt,
		&i.GameSetting.GameID,
		&i.GameSetting.Rounds,
		&i.GameSetting.TimePerRound,
		&i.GameSetting.Difficulty,
		&i.GameSetting.Category,
		&i.GameSetting.AiModel,
		&i.GameSetting.MaxPlayers,
		&i.GameSetting.UpdatedAt,
		&i.PlayerCount,
	)
	return &i, err
}

const ListGamePlayers = `-- name: ListGamePlayers :many
SELECT p.user_id, u.username, p.joined_at
FROM game_players p
JOIN users u ON u.id = p.user_id
WHERE p.game_id = $1
ORDER BY p.joined_at, p.user_id
`

type ListGamePlayersRow struct {
	UserID   pgtype.UUID
	Username string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) ListGamePlayers(ctx context.Context, gameID pgtype.UUID) ([]*ListGamePlayersRow, error) {
	rows, err := q.db.Query(ctx, ListGamePlayers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListGamePlayersRow{}
	for rows.Next() {
		var i ListGamePlayersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGamesByStatus = `-- name: ListGamesByStatus :many
SELECT g.id, g.room_code, g.host_id, g.status, g.created_at, g.updated_at, g.started_at, s.game_id, s.rounds, s.time_per_round, s.difficulty, s.category, s.ai_model, s.max_players, s.updated_at,
       (SELECT COUNT(*) FROM game_players p WHERE p.game_id = g.id)::int AS player_count
FROM games g
JOIN game_settings s ON s.game_id = g.id
WHERE g.status = $1
ORDER BY g.created_at DESC, g.id
LIMIT $2
`

type ListGamesByStatusParams struct {
	Status string
	Limit  int32
}

type ListGamesByStatusRow struct {
	Game        Game
	GameSetting GameSetting
	PlayerCount int32
}

func (q *Queries) ListGamesByStatus(ctx context.Context, arg ListGamesByStatusParams) ([]*ListGamesByStatusRow, error) {
	rows, err := q.db.Query(ctx, ListGamesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListGamesByStatusRow{}
	for rows.Next() {
		var i ListGamesByStatusRow
		if err := rows.Scan(
			&i.Game.ID,
			&i.Game.RoomCode,
			&i.Game.HostID,
			&i.Game.Status,
			&i.Game.CreatedAt,
			&i.Game.UpdatedAt,
			&i.Game.StartedAt,
			&i.GameSetting.GameID,
			&i.GameSetting.Rounds,
			&i.GameSetting.TimePerRound,
			&i.GameSetting.Difficulty,
			&i.GameSetting.Category,
			&i.GameSetting.AiModel,
			&i.GameSetting.MaxPlayers,
			&i.GameSetting.UpdatedAt,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LockGameByID = `-- name: LockGameByID :one
SELECT g.id, g.room_code, g.host_id, g.status, g.created_at, g.updated_at, g.started_at, s.game_id, s.rounds, s.time_per_round, s.difficulty, s.category, s.ai_model, s.max_players, s.updated_at,
       (SELECT COUNT(*) FROM game_players p WHERE p.game_id = g.id)::int AS player_count
FROM games g
JOIN game_settings s ON s.game_id = g.id
WHERE g.id = $1
FOR UPDATE OF g
`

type LockGameByIDRow struct {
	Game        Game
	GameSetting GameSetting
	PlayerCount int32
}

// Row-locks the game so membership and status changes are serialized.
func (q *Queries) LockGameByID(ctx context.Context, id pgtype.UUID) (*LockGameByIDRow, error) {
	row := q.db.QueryRow(ctx, LockGameByID, id)
	var i LockGameByIDRow
	err := row.Scan(
		&i.Game.ID,
		&i.Game.RoomCode,
		&i.Game.HostID,
		&i.Game.Status,
		&i.Game.CreatedAt,
		&i.Game.UpdatedAt,
		&i.Game.StartedAt,
		&i.GameSetting.GameID,
		&i.GameSetting.Rounds,
		&i.GameSetting.TimePerRound,
		&i.GameSetting.Difficulty,
		&i.GameSetting.Category,
		&i.GameSetting.AiModel,
		&i.GameSetting.MaxPlayers,
		&i.GameSetting.UpdatedAt,
		&i.PlayerCount,
	)
	return &i, err
}

const RemoveGamePlayer = `-- name: RemoveGamePlayer :execrows
DELETE FROM game_players WHERE game_id = $1 AND user_id = $2
`

type RemoveGamePlayerParams struct {
	GameID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RemoveGamePlayer(ctx context.Context, arg RemoveGamePlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, RemoveGamePlayer, arg.GameID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateGameHost = `-- name: UpdateGameHost :exec
UPDATE games SET host_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdateGameHostParams struct {
	ID     pgtype.UUID
	HostID pgtype.UUID
}

func (q *Queries) UpdateGameHost(ctx context.Context, arg UpdateGameHostParams) error {
	_, err := q.db.Exec(ctx, UpdateGameHost, arg.ID, arg.HostID)
	return err
}

const UpdateGameSettings = `-- name: UpdateGameSettings :exec
UPDATE game_settings
SET rounds         = $2,
    time_per_round = $3,
    difficulty     = $4,
    category       = $5,
    ai_model       = $6,
    max_players    = $7,
    updated_at     = NOW()
WHERE game_id = $1
`

type UpdateGameSettingsParams struct {
	GameID       pgtype.UUID
	Rounds       int16
	TimePerRound int16
	Difficulty   string
	Category     string
	AiModel      string
	MaxPlayers   int16
}

func (q *Queries) UpdateGameSettings(ctx context.Context, arg UpdateGameSettingsParams) error {
	_, err := q.db.Exec(ctx, UpdateGameSettings,
		arg.GameID,
		arg.Rounds,
		arg.TimePerRound,
		arg.Difficulty,
		arg.Category,
		arg.AiModel,
		arg.MaxPlayers,
	)
	return err
}

const UpdateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games
SET status     = $1::varchar,
    started_at = CASE WHEN $1::varchar = 'in_progress' THEN NOW() ELSE started_at END,
    updated_at = NOW()
WHERE id = $2
`

type UpdateGameStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.Exec(ctx, UpdateGameStatus, arg.Status, arg.ID)
	return err
}
