// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	ID            pgtype.UUID
	Slug          string
	Title         string
	Description   string
	Category      string
	Difficulty    string
	Constraints   []byte
	JudgeCriteria []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Game struct {
	ID        pgtype.UUID
	RoomCode  string
	HostID    pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	StartedAt pgtype.Timestamptz
}

type GamePlayer struct {
	GameID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type GameSetting struct {
	GameID       pgtype.UUID
	Rounds       int16
	TimePerRound int16
	Difficulty   string
	Category     string
	AiModel      string
	MaxPlayers   int16
	UpdatedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Username      string
	Email         string
	Password      string
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type VerificationToken struct {
	ID        int64
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
