// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            pgtype.UUID
	Email         string
	Password      string
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type VerificationToken struct {
	ID        int64
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
