// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (*VerificationToken, error)
	DeleteExpiredTokens(ctx context.Context) error
	DeleteVerificationToken(ctx context.Context, token string) error
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	GetVerificationToken(ctx context.Context, token string) (*VerificationToken, error)
	SetEmailVerified(ctx context.Context, id pgtype.UUID) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
}

var _ Querier = (*Queries)(nil)
