// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, CreateRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const GetActiveRefreshTokenUserID = `-- name: GetActiveRefreshTokenUserID :one
SELECT user_id
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetActiveRefreshTokenUserID(ctx context.Context, tokenHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, GetActiveRefreshTokenUserID, tokenHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const RevokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, RevokeRefreshToken, tokenHash)
	return err
}

const RotateRefreshToken = `-- name: RotateRefreshToken :one
WITH revoked AS (
    UPDATE refresh_tokens
    SET revoked_at = NOW()
    WHERE refresh_tokens.token_hash = $1
      AND refresh_tokens.revoked_at IS NULL
      AND refresh_tokens.expires_at > NOW()
    RETURNING refresh_tokens.user_id
)
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
SELECT $2, user_id, $3
FROM revoked
RETURNING user_id
`

type RotateRefreshTokenParams struct {
	TokenHash   string
	TokenHash_2 string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, RotateRefreshToken, arg.TokenHash, arg.TokenHash_2, arg.ExpiresAt)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
