// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (*VerificationToken, error) {
	row := q.db.QueryRow(ctx, CreateVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM verification_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, DeleteExpiredTokens)
	return err
}

const DeleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens WHERE token = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, DeleteVerificationToken, token)
	return err
}

const GetVerificationToken = `-- name: GetVerificationToken :one
SELECT id, user_id, token, expires_at, created_at FROM verification_tokens WHERE token = $1
`

func (q *Queries) GetVerificationToken(ctx context.Context, token string) (*VerificationToken, error) {
	row := q.db.QueryRow(ctx, GetVerificationToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}
